name: Workflows Automatic Deploy

on:
  push:
    branches:
      - main

jobs:
  entrega:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Deploy
        run: npm run deploy
